### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by Cogitri** [tuberry/shuzhi#1]
Hello,

I just installed the extension but nothing has changed about my background. What do I have to do to set up the extension after enabling it?
I'm using GNOME 40.

Thanks!

**Comment by tuberry** [comment]
1. Select the `Picture location` for saving the generated picture first;
 2. Fill the `Text command` entry for generating text, for example, `echo "test"`;

**Comment by Cogitri** [comment]
Oh, somehow I had assumed the extension would automatically set the wallpaper for me.

For some reason the file picker that is opened when I select `Picture Location` wants me to select a file when shuzhi seems to expect a folder - setting it to folder via dconf-editor seems to fix that.

**Comment by Cogitri** [comment]
Maybe the extensions could just choose a location in ~/.cache by default - I'm not quite sure why the user even has to set the directory.

**Comment by tuberry** [comment]
> Oh, somehow I had assumed the extension would automatically set the wallpaper for me.
>
> For some reason the file picker that is opened when I select `Picture Location` wants me to select a file when shuzhi seems to expect a folder - setting it to folder via dconf-editor seems to fix that.

This is a bug caused by my oversight, I will fix it soon.

> Maybe the extensions could just choose a location in ~/.cache by default - I'm not quite sure why the user even has to set the directory.

The extension generate two images so that it’s best to own a standalone folder. I can't find such a location that everyone likes, so it's best to have a choice. :)

**Comment by Cogitri** [comment]
Great, thanks for looking into this and thanks for the extension! :)
