### ISSUE TITLE
Poem name and poet's name do not follow the font size setting.

### ISSUE THREAD

**Issue by qvshuo** [tuberry/shuzhi#10]
I'm using a 4k resolution screen, so I need to set the font to a larger size, like 72.
But only the font size of the verse is affected by this setting. The font size of the poem name and the poet's name remains relatively small. It just seems incongruous.
I hope you can take the time to optimize it. Thank you.

System: Fedora 35
Gnome version: 41.2
shuzhi version: the latest

**Comment by qvshuo** [comment]
Excellent job! Coule you update the extension on the Gnome extension site?

**Comment by tuberry** [comment]
Nope, this extension doesn't fully meet e.g.o's review guidelines, and it probably won't be updated on this site anymore.

**Comment by qvshuo** [comment]
> Nope, this extension doesn't fully meet e.g.o's review guidelines, and it probably won't be updated on this site anymore.

got it. thank you.
