### ISSUE TITLE
No poem displayed, only distribution logo

### ISSUE THREAD

**Issue by eailfly** [tuberry/shuzhi#11]
After install extension, no poem displayed, just an arch logo as I'm using arch.
![2021-12-29 12-02-39屏幕截图](https://user-images.githubusercontent.com/3424220/147626456-ea74d44f-3e6c-4267-a6c0-2fc60f3d36b6.png)

This is my setting:
![2021-12-29 12-05-32屏幕截图](https://user-images.githubusercontent.com/3424220/147626474-583ae727-c180-4a45-9ede-4cc9dda04114.png)

Am I missing anything?

**Comment by tuberry** [comment]
https://github.com/tuberry/shuzhi#note
