### ISSUE TITLE
[feature-request] Can backport to macOS?

### ISSUE THREAD

**Issue by kamusis** [tuberry/shuzhi#13]
Maybe it's not a friendly request, but I really like the wallpapers generated by this great gnome extension, I personally use Ubuntu and macOS both, so ... it's very appreciated if I can get a shuzhi app for macOS, or at least can you offer a function that can keep every png file when refreshed, instead of overwriting the previous one.
Thank you so much.

**Comment by tuberry** [comment]
> so ... it's very appreciated if I can get a shuzhi app for macOS

Thanks. Unfortunately, I don't have a Mac, but there is a [Jizhi](https://apps.apple.com/hk/app/%E5%87%A0%E6%9E%9D-%E6%84%BF%E5%90%9B%E5%A4%9A%E9%87%87%E6%92%B7/id1552874203) app in the AppStore which could be what you want.

> or at least can you offer a function that can keep every png file when refreshed, instead of overwriting the previous one.

That could take up a large amount of hard drive space over time. If you want a copy after each refresh, this fish script might help:
```fish
set path ~/Pictures/shuzhi/shuzhi-light
while inotifywait -q -e close_write $path.png
    cp -a $path{,-(date +%Y%m%d-%H%M%S)}.png
end
```

**Comment by kamusis** [comment]
Hi tuberry
thanks for the reply. I'll try Jizhi.
maybe offer an option let the user can set "how many" pictures can be reserved will resolve the hard drive space concern. to say, the default setting is only 1, when archive the max value, the new one will overwrite the oldest one.
