### ISSUE TITLE
Little Fedora icon in the middle of wallpaper?

### ISSUE THREAD

**Issue by mkutev** [tuberry/shuzhi#15]
How can I get rid of this little Fedora icon that is stuck in the middle of the wallpaper?
Doesn't matter if I generate new wallpaper or change resolution, it is always there.

Thanks in advance, the extension is very nice.

![Screenshot from 2022-09-21 13-47-18](https://user-images.githubusercontent.com/23249437/191607359-eb828f9d-1b19-4707-af2c-e5c27d621dc7.png)

**Comment by tuberry** [comment]
This is the default behavior when generated text missing, please set the text command to `echo " " ` to avoid it.

For more info, see https://github.com/tuberry/shuzhi#note.

**Comment by mkutev** [comment]
Thank you!
