### ISSUE TITLE
Feature request: 让字间距可以调整

### ISSUE THREAD

**Issue by everyx** [tuberry/shuzhi#16]
这个插件实在是太棒了，就是设置字体为 Noto Serif CJK SC 的时候，感觉字间距有点密，如果能调整就更好了，感谢

![图片](https://user-images.githubusercontent.com/1665522/201278254-50707f53-6111-4ce9-974e-ffdacd3bd8ac.png)

**Comment by tuberry** [comment]
可能是硬编码的1.05倍行间距显得字间距太小，现已移除：

![图片](https://user-images.githubusercontent.com/17917040/201318573-73856486-9128-4738-8fde-4484e75d7a25.png)

可以直接修改 [Pango Markup](https://docs.gtk.org/Pango/pango_markup.html)。

减小 line_height ：

```bash
echo '<span line_height="0.8">疏影横斜水清浅\n暗香浮动<span bgcolor=\"green\">月</span>黄昏</span>\n<span font=\"0.45em\">「山园小梅」 <span bgcolor=\"#b45a56\" fgcolor=\"SZ_BGCOLOR\">林逋</span></span>"'
```

![图片](https://user-images.githubusercontent.com/17917040/201318972-1a4012e8-f738-4d69-b43b-7789377afa05.png)
也可以增加字间距 letter_spacing (1024的倍数)：

```bash
echo '<span letter_spacing="4096">疏影横斜水清浅\n暗香浮动<span bgcolor=\"green\">月</span>黄昏</span>\n<span font=\"0.45em\">「山园小梅」 <span bgcolor=\"#b45a56\" fgcolor=\"SZ_BGCOLOR\">林逋</span></span>"'
```

![图片](https://user-images.githubusercontent.com/17917040/201320103-2dd4cea9-8ad8-48e6-86e7-f58b7a71a625.png)

因为涉及特定字体可以自行修改 [shuzhi.sh](https://github.com/tuberry/shuzhi/blob/0caa9ed06058261ae50d204d468432025a9a3707/shuzhi%40tuberry/shuzhi.sh#L13) 放到 PATH 下使用:

```bash
printf '{"vtext":"<span letter_spacing=\"4096\">%s%s</span>","htext":"<span letter_spacing=\"4096\">%s\\n%s</span>"}' "$vcontent" "$title" "$content" "$title"
```

**Comment by everyx** [comment]
修改了一下，协调多了 😁

![图片](https://user-images.githubusercontent.com/1665522/201449371-a44e738c-c2ed-4602-a699-7242f6d59ef4.png)


```bash
#!/bin/bash
# by tuberry & mechtifs

# API from https://github.com/xenv/gushici
res=$(curl -s https://v1.jinrishici.com/all.json)
content=$(echo "$res" | grep -Po '(?<="content" : ")[^"]*')
test -z "$content" && exit 1
author=$(echo "$res" | grep -Po '(?<="author" : ")[^"]*')
origin=$(echo "$res" | grep -Po '(?<="origin" : ")[^"]*' | sed -r 's/\ //g')
gap='<span font=\"0.54em\"> </span>\n'
# `SZ_BGCOLOR` is the bgcolor of wallpaper
title='<span font=\"0.45em\">'「$origin」'<span bgcolor=\"#b45a56\" fgcolor=\"SZ_BGCOLOR\"> '$author' </span></span>'
vcontent=$(echo "$content" | sed -r 's/[，。：；？、！]/\n/g;s/[《》“”]//g;' | sed -r '/^\s*$/d' | sed -z 's/\n/\\n/g')
printf '{"vtext":"<span line_height=\\"1.05\\" letter_spacing=\\"7168\\">%s%s%s</span>","htext":"<span line_height=\\"1.05\\" letter_spacing=\\"7168\\">%s\\n%s%s</span>"}' "$vcontent" "$gap" "$title" "$content" "$gap" "$title"
```
