### ISSUE TITLE
多屏时应使用最大分辨率的屏幕来生成壁纸

### ISSUE THREAD

**Issue by everyx** [tuberry/shuzhi#17]
目前好像是根据主显示器的分辨率设置的，我的外接显示器就会出现黑边。

另外还有一个问题，经常会出现如图中的这样不显示诗词的情况，但是我运行脚本输出又是正常的，`journalctl /usr/bin/gnome-shell -r` 查看日志也没有什么和本插件相关报错的，不知道是什么原因。

主屏填充完好
![图片](https://user-images.githubusercontent.com/1665522/202349838-81173f83-4c21-4d75-897a-64c9dea520f1.png)

副屏上下有黑边
![图片](https://user-images.githubusercontent.com/1665522/202349872-4dd3c365-b89f-48bc-8551-e5488e563571.png)

**Comment by tuberry** [comment]
> 另外还有一个问题，经常会出现如图中的这样不显示诗词的情况，但是我运行脚本输出又是正常的，journalctl /usr/bin/gnome-shell -r 查看日志也没有什么和本插件相关报错的，不知道是什么原因。

没有复现。现在加了 log 下次出现 `journalctl -fo cat /usr/bin/gnome-shell` 应该就有报错了。如果问题和上游今日诗词 API 相关可考虑使用离线数据，参考[_shuzhi.fish](https://github.com/tuberry/shuzhi/blob/main/_shuzhi.fish).

**Comment by everyx** [comment]
> > 另外还有一个问题，经常会出现如图中的这样不显示诗词的情况，但是我运行脚本输出又是正常的，journalctl /usr/bin/gnome-shell -r 查看日志也没有什么和本插件相关报错的，不知道是什么原因。
> 
> 没有复现。现在加了 log 下次出现 `journalctl -fo cat /usr/bin/gnome-shell` 应该就有报错了。如果问题和上游今日诗词 API 相关可考虑使用离线数据，参考[_shuzhi.fish](https://github.com/tuberry/shuzhi/blob/main/_shuzhi.fish).

好的，我先安装一下 git 版本，下次有问题再来提交

**Comment by everyx** [comment]
> 好的，我先安装一下 git 版本，下次有问题再来提交

日志有了

```js
JS ERROR: shuzhi: Error
_execute@/usr/share/gnome-shell/extensions/shuzhi@tuberry/extension.js:285:42
async*_getMotto@/usr/share/gnome-shell/extensions/shuzhi@tuberry/extension.js:304:51
async*_setMotto@/usr/share/gnome-shell/extensions/shuzhi@tuberry/extension.js:318:18
set refresh/this._refreshId<@/usr/share/gnome-shell/extensions/shuzhi@tuberry/extension.js:257:62
```

**Comment by tuberry** [comment]
脚本退出状态异常但没有报错信息，应该是[这行](https://github.com/tuberry/shuzhi/blob/90df351c0edfeea8c76e8a6c0d0dbc8c9f804696/shuzhi%40tuberry/shuzhi.sh#L7)。 可能是`curl` 没取到消息或者`grep`解析失败，返回的JSON格式固定前一种可能性更大。

可在`curl`后加个 fallback:
```bash
[ $? -ne 0 ] && res=$(cat <<-END
{
  "content" : "content",
  "origin" : "origin",
  "author" : "author"
}
END
) || echo $res >> /tmp/shuzhi.log
```
再次异常出现 fallback 说明是`curl`的问题，否则就是 `grep` 的问题（查看 shuzhi.log 是否格式有异）。
