### ISSUE TITLE
使用shu zhi过程中出现的问题

### ISSUE THREAD

**Issue by Skatl** [tuberry/shuzhi#19]

**Comment by tuberry** [comment]
请将文本命令设为 `shuzhi.sh`, 参见[说明](https://github.com/tuberry/shuzhi#note).

**Comment by Skatl** [comment]
我已经尝试过，这不奏效，会不会是由于从extension manager的browser里下载的版本不完整

**Comment by tuberry** [comment]
修改后需要按回车提交更改，可以重新打开设置界面看看是否设置成功。

![pic](https://user-images.githubusercontent.com/17917040/204965249-8a001f63-1494-4ccf-8211-e526ff1979ca.png)

还不奏效可以在终端运行
```bash
bash ~/.local/share/gnome-shell/extensions/shuzhi@tuberry/shuzhi.sh
```
看看输出是否正常
