### ISSUE TITLE
Allow setting certain times for switching light/dark mode

### ISSUE THREAD

**Issue by Cogitri** [tuberry/shuzhi#2]
I'm not quite sure how the "auto" heuristic works, but it'd be great if the extension also allowed switching at certain times or when the sun rises

**Comment by tuberry** [comment]
If `auto` is selected, it will switch to the light/dark mode when the `Night Light` (in `Settings`>`Display`)  is on. I think the system has such a mechanism that there is no need to add additional time settings.

**Comment by Cogitri** [comment]
Ah, fair, I didn't realise that `auto` was linked to Night Light, maybe there could be a tooltip or similiar for that (or maybe a warning if the user doesn't have night light enabled but chose auto?)

**Comment by Cogitri** [comment]
Thanks! :)
