### ISSUE TITLE
建议：对文字部分设置最大高度，超出高度自动折行

### ISSUE THREAD

**Issue by everyx** [tuberry/shuzhi#20]
有些名字很长，就把正文也顶没了，见下图，能否设置一下最大高度？

一些想法：
1. 取屏幕高度的某个比例
2. 屏幕高度 -  固定的 margin 值
3. 以上的比例或者固定的 margin 值可在界面中

另：计算时应取所有屏幕中最小的高度作为屏幕高度

![图片](https://user-images.githubusercontent.com/1665522/208222431-0c0ebe13-f8d1-4acb-a677-394746b2e1c8.png)

**Comment by tuberry** [comment]
抱歉回复晚了。

此次[提交](https://github.com/tuberry/shuzhi/commit/ed2c327037d139a3ca1e6385785d88205fb1f5de)中已经调整位置以保证文本起始于页面内。图片格式也改用了svg，对不同分辨率应该更友好些，但要用到部分[gjs](https://gitlab.gnome.org/GNOME/gjs)的新特性，请自行编译其git版本。

至于限定高度，强扭的瓜不一定甜。可自行换行，参考[这里](https://github.com/tuberry/shuzhi/blob/c60d15dea0a67b641468896e0fab299abe914abc/_shuzhi.fish#L46-L52)：
![image](https://user-images.githubusercontent.com/17917040/209347365-24982fe1-b81e-40ef-abc0-3aed23d50e46.png)
