### ISSUE TITLE
desktop notification

### ISSUE THREAD

**Issue by trampover** [tuberry/shuzhi#21]
#!/bin/bash
# by tuberry & mechtifs

# API from https://github.com/xenv/gushici
res=$(curl -s https://v1.jinrishici.com/all.json)
content=$(echo $res | grep -Po '(?<="content" : ")[^"]*')
test -z $content && exit 1
author=$(echo $res | grep -Po '(?<="author" : ")[^"]*')
origin=$(echo $res | grep -Po '(?<="origin" : ")[^"]*' | sed -r 's/\ //g')
gap='<span font=\"0.4em\"> </span>\n'
# `SZ_BGCOLOR` is the bgcolor of wallpaper
title='<span font=\"0.45em\">'「$origin」'<span bgcolor=\"#b45a56\" fgcolor=\"SZ_BGCOLOR\">'$author'</span></span>'
vcontent=$(echo $content | sed -r 's/[，。：；？、！]/\n/g;s/[《》“”]//g;' | sed -r '/^\s*$/d' | sed -z 's/\n/\\n/g')
printf '{"vtext":"%s%s%s","htext":"%s\\n%s%s"}' "$vcontent" "$gap" "$title" "$content" "$gap" "$title"

# 同时显示通知,需要libnotify-bin支持

res=$(notify-send "$author-「$origin」" "<b>$content</b>" -c device -u critical -i $HOME/.local/share/gnome-shell/extensions/shuzhi@tuberry/icons/florette-symbolic.svg)

#同时播放提示音
res=$(canberra-gtk-play -f /usr/share/sounds/gnome/default/alerts/swing.ogg)

**Comment by trampover** [comment]
![fds](https://user-images.githubusercontent.com/16641676/211879405-d4f8bcea-3839-4e1f-95d8-37df8f80aab4.png)

截图如下

**Comment by tuberry** [comment]
添加通知和播放声音不太符合 [minimize distractions](https://help.gnome.org/users/gnome-help/stable/shell-introduction.html) 的设计理念，会给不需要此功能的人造成困扰。

如果有需要可自行将脚本放到用户`PATH`下使用，
