### ISSUE TITLE
Feature Request: 自动配置当前壁纸的颜色作为 GTK/Gnome Shell 的 Accent Colors

### ISSUE THREAD

**Issue by everyx** [tuberry/shuzhi#23]
当前使用 https://github.com/demiskp/custom-accent-colors 这个插件来设置颜色，如果能根据 shuzhi 的壁纸颜色自动配置那就太棒了 😄

**Comment by tuberry** [comment]
Gnome Shell 没有专门的 Accent Color API，要任意颜色的话目前只好改上游[SASS](https://gitlab.gnome.org/GNOME/gnome-shell-sass)重新编译个新主题，或者找出所有用 Accent Color 的组件子集文件可以小点，但都不算什么办法。要实现这个功能需要上游先弄个[类Gtk的API](https://github.com/demiskp/custom-accent-colors/blob/main/custom-accent-colors%40demiskp/resources/magenta/gtk.css) :-)

**Comment by everyx** [comment]
目前可行的方案的确都比较 hack，另外一个类似的插件 https://github.com/avanisubbiah/material-you-theme 也应该是这样做的，区别在于主题和样式都是自动生成的。上游能提供 API 的可能性感觉非常小，也许可以 fork [demiskp/custom-accent-colors](https://github.com/demiskp/custom-accent-colors)，创建一个新的插件，提供通过 shell 修改 accent color 的能力，然后在 shuzhi 的文本命令脚本中处理自动切换

**Comment by tuberry** [comment]
Accent Color 能接受 Hack 的话，可以用[user-theme-x](https://github.com/tuberry/user-theme-x)再糊个生成css的脚本：
<details>
  <summary>参考脚本</summary>

```fish
#!/usr/bin/fish
# by tuberry

argparse --ignore-unknown c/color= -- $argv
if not set -q _flag_c
    echo 'no --color given'
    exit 1
end

if test -d gnome-shell
    cd gnome-shell # && git pull --quiet
else
    git clone --depth=1 --no-checkout https://github.com/GNOME/gnome-shell.git
    cd gnome-shell && git sparse-checkout set data/theme/ && git checkout main
end

sed -e "s/fill:#3584e4/fill:$_flag_c/g" data/theme/toggle-on.svg >~/.config/gnome-shell/toggle-on.svg

sed -ie "/selected_bg_color:/s/: .*/: $_flag_c;/" data/theme/gnome-shell-sass/_colors.scss
sed -ie "s/resource\:\/\/\/org\/gnome\/shell\/theme\/toggle-on.svg/.\/toggle-on.svg/g" data/theme/gnome-shell-sass/widgets/_switches.scss
sassc -a data/theme/gnome-shell.scss ~/.config/gnome-shell/gnome-shell.css

git checkout . --quiet
cd ..
```
</details>

另外有两个颜色相关的问题：
1. 部分颜色（如深灰）不适合作为 Accent Color
2. 如何从多种颜色（如 Blobs）中决出 Accent Color

**Comment by everyx** [comment]
> 1.部分颜色（如深灰）不适合作为 Accent Color
> 2. 如何从多种颜色（如 Blobs）中决出 Accent Color


从给定的单个颜色或者图片中提取色板，并获取符合对比度的方法也许可以参考 https://github.com/material-foundation/material-color-utilities

**Comment by tuberry** [comment]
看了一下不是一两行的事，像[avanisubbiah/material-you-theme](https://github.com/avanisubbiah/material-you-theme)那样作为依赖引入个人感觉蛮难维护的 :-( 。[这官网](https://m3.material.io/theme-builder#/dynamic)传图像似乎不起作用所以效果未知。如果有命令行版本直接从图片提取颜色糊个脚本放到文本生成命令里 `nohup` 延迟执行应该能达到目的。
