### ISSUE TITLE
Error in rendering of text command

### ISSUE THREAD

**Issue by InfoSimoneGiusti** [tuberry/shuzhi#27]
When text command contains "em" string, it's interpreted as 0.
When text contains .em, it is intepreted as NaN.

For example: `echo problem` will be rendered as probl0.

![Schermata del 2023-10-24 14-45-30](https://github.com/tuberry/shuzhi/assets/93975423/01f5f3ce-435a-4303-910e-d4b705c92b62)

**Comment by tuberry** [comment]
Fixed in the latest commit. 
If you're using GNOME 45, you could [install it from GitHub](https://github.com/tuberry/shuzhi#manual), otherwise, you should correct the [regex](https://github.com/tuberry/shuzhi/blob/0bc644e962b0a91354ba76e762b068c6cb10ecf7/src/extension.js#L26) manually:
```js
const em2pg = (x, y) => x.replaceAll(/\b(\d+\.?\d*)em\b/g, (_m, p1) => `${y * p1}`)
```
