### ISSUE TITLE
support `SZ_FGCOLOR`

### ISSUE THREAD

**Issue by everyx** [tuberry/shuzhi#28]
Currently we support using the `SZ_BGCOLOR` variable in scripts, is it possible to add foreground color support `SZ_FGCOLOR`?

**Comment by tuberry** [comment]
`SZ_FGCOLOR` is used for text without fgcolor specified, and I am curious about the use cases for supporting it in scripts.

The fgcolor /bgcolor is static in the same style (light/dark). Would introducing light/dark text like horizontal/vertical text cover this? 

By the way, `SZ_BGCOLOR` was introduced as an ugly workaround, which lacked rounded corners and transparency, for seal like  `background-clip: text` CSS, so I plan to deprecate it and handle this part of the text separately.

**Comment by everyx** [comment]
> The fgcolor /bgcolor is static in the same style (light/dark). Would introducing light/dark text like horizontal/vertical text cover this?

I just want:
- Accent color from GNOME accent color or shuzhi's current color for background (`SZ_FGCOLOR`)
- Accent contrast color for text (`SZ_BGCOLOR`)

![图片](https://github.com/user-attachments/assets/87ef2bb1-3b8b-4742-9284-82ccf95c5e1a)

**Comment by tuberry** [comment]
IIUC, does `SZ_FGCOLOR` refer to the current accent color instead of the regular text color (black in the screenshot)?

**Comment by everyx** [comment]
> IIUC, does `SZ_FGCOLOR` refer to the current accent color instead of the regular text color (black in the screenshot)?

Yes, although the name `SZ_FGCOLOR` is easily misleading
