### ISSUE TITLE
Dual Monitor

### ISSUE THREAD

**Issue by BatmansGehilfe** [tuberry/shuzhi#3]
Hi there. Wonderful extension, love it!
I just have one issue: When I have two monitors attached the resulting wallpaper has the width of both monitors combined instead of just one of them. So the wallpaper is 3840 px instead of 1920 px wide. Can this be fixed or do you need more information on this?

Edit: I use Gnome 40 on ArcoLinux (Arch based)

**Comment by tuberry** [comment]
Thanks.

I think gnome-shell recognizes the joined monitors as a single monitor, and we could have an additional resolution setting if so. Could you show me the output of `global.display.get_size()` in lookingGlass (press <kbd>Alt</kbd> + <kbd>F2</kbd> and type `lg` then press <kbd>Enter</kbd>)

**Comment by BatmansGehilfe** [comment]
That seems very likely. The output of `global.display.get_size()` reads `r(0) = 3840,1080`

**Comment by tuberry** [comment]
You can try it from GitHub now. :)

**Comment by BatmansGehilfe** [comment]
Works like a charm - thank you!
