### ISSUE TITLE
Request to draft a new release for GNOME 40

### ISSUE THREAD

**Issue by AlynxZhou** [tuberry/shuzhi#6]
Hi, I am packaging stable release of this project on AUR (https://aur.archlinux.org/packages/gnome-shell-extension-shuzhi/), but I found the last release is targeting GNOME 3.38, and GNOME 40 will disable extensions who does not have version 40 in their metadata, also it seems there are a lot of new commits after the latest release.

This extension on https://extensions.gnome.org/extension/3985/shu-zhi/ has a release for GNOME 40, could you please also make a release on GitHub so I can package it? Thanks.

**Comment by tuberry** [comment]
Thanks. :)

**Comment by AlynxZhou** [comment]
Package also available on Arch Linux CN repo: https://github.com/archlinuxcn/repo/commit/ff358a40f7d513b4f8ff8195b121233862def7a1

**Comment by tuberry** [comment]
There was a bug in the Makefile, therefore the tag 40 has been updated to the latest [commit](https://github.com/tuberry/shuzhi/commit/76c63da4bb95d6edfe4bbba0f89f662695315bb9) now. Sorry for the inconvenience and thanks again.

**Comment by AlynxZhou** [comment]
> There was a bug in the Makefile, therefore the tag 40 has been updated to the latest [commit](https://github.com/tuberry/shuzhi/commit/76c63da4bb95d6edfe4bbba0f89f662695315bb9) now. Sorry for the inconvenience and thanks again.

Hi, I think you should draft another release with a minor version, because package tools assume that a released tarball won't change and will refuse to re-download and package the same version. Thanks!
